name: build-and-test-gfn
on: [push]
jobs:
  build:
    strategy:
      matrix:
        version: [1.24.5]
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go ${{ matrix.os }}
      uses: actions/setup-go@v6
      with:
        go-version: '${{ matrix.version }}'
      id: go

    - name: checkout
      uses: actions/checkout@v4

    - name: build
      run: go build

    - name: test
      run: make test

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v6
        with:
          go-version: 1.24
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
